version: '3'
services:
  db-app:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: PetitionAppDB
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: app
      MYSQL_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
networks:
  default:
    driver: bridge
