services:
  db-app:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: PetitionAppDB
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  back:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-app:3306/PetitionAppDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - .:/app # This volume mounts your application code

volumes:
  db-data: # This defines a named volume for MySQL data
