version: '3'
services:
  db-app:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: PetitionAppDB
      MYSQL_ROOT_PASSWORD: 'verysecret'
      MYSQL_USER: app
      MYSQL_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  back:
    build:
      context: .
      dockerfile: Dockerfile
    image: "petition:${DOCKER_IMAGE_TAG}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-app:3306/PetitionAppDB?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 9090:9090
    depends_on:
      - db-app
    volumes:
      - .:/app