name: Create Pull Request Workflow

on:
  push:
    branches:
      - testBranch  # Replace with your branch name

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "feature-branch"  # Replace with your branch name
          destination_branch: "main"  # Replace with your target branch name
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated Pull Request"
          pr_body: "This is an automated pull request to merge changes from feature-branch to main."
          destination_repo_owner: "DonLofto"  # Replace with the owner of the main repository
          destination_repo_name: "DevOpsProject"  # Replace with the name of the main repository
